#!/bin/bash
#SBATCH --job-name=esvit_swin_tiny_7x7_bn_2node
#SBATCH -p gpu
#SBATCH -N 2
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH -t 3-11:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o esvit_swin_tiny_7x7_bn_2node.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

#python main_esvit_mnodes.py --num_nodes 2 --num_gpus_per_node 4 --data_path /projects/2/managed_datasets/imagenet/train/ --output_dir ~/project_space/esvit/output/esvit_exp/ssl/slak_tiny_imagenet_7x7/ --batch_size_per_gpu 64 --arch SLaK_tiny --kernel_size 7 7 7 7 100 --bn True  --zip_mode True --epochs 300 --teacher_temp 0.07 --warmup_epochs 10 --warmup_teacher_temp_epochs 30 --norm_last_layer false --cfg experiments/imagenet/swin/swin_tiny_patch4_window7_224.yaml --use_dense_prediction True

python -m torch.distributed.launch --nproc_per_node=1 \
           --nnodes=2 --node_rank=0 --master_addr="192.168.1.1"  \
           --master_port=1234 main_esvit_mnodes.py --data_path /projects/2/managed_datasets/imagenet/train/ \
           --output_dir ~/project_space/esvit/output/esvit_exp/ssl/slak_tiny_imagenet_7x7/ \
           --batch_size_per_gpu 64 --arch SLaK_tiny --kernel_size 7 7 7 7 100 --bn True  \
           --zip_mode True --epochs 300 --teacher_temp 0.07 --warmup_epochs 10 \
           --warmup_teacher_temp_epochs 30 --norm_last_layer false \
           --cfg experiments/imagenet/swin/swin_tiny_patch4_window7_224.yaml --use_dense_prediction True

python -m torch.distributed.launch --nproc_per_node=1 \
           --nnodes=2 --node_rank=1 --master_addr="192.168.1.1"  \
           --master_port=1234 main_esvit_mnodes.py --data_path /projects/2/managed_datasets/imagenet/train/ \
           --output_dir ~/project_space/esvit/output/esvit_exp/ssl/slak_tiny_imagenet_7x7/ \
           --batch_size_per_gpu 64 --arch SLaK_tiny --kernel_size 7 7 7 7 100 --bn True  \
           --zip_mode True --epochs 300 --teacher_temp 0.07 --warmup_epochs 10 \
           --warmup_teacher_temp_epochs 30 --norm_last_layer false \
           --cfg experiments/imagenet/swin/swin_tiny_patch4_window7_224.yaml --use_dense_prediction True

 source deactivate