#!/bin/bash
#SBATCH --job-name=esvit_swin_tiny_7x7_bn_100epochs
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 3-11:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o esvit_swin_tiny_7x7_bn_100epochs.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

DATA_PATH=/projects/2/managed_datasets/imagenet/
PROJ_PATH=your_esvit_project_path
OUT_PATH=~/project_space/esvit/output/esvit_exp/ssl/swin_tiny_imagenet_100epochs/

python -m torch.distributed.launch --nproc_per_node=4 main_esvit.py --arch swin_tiny \
--data_path $DATA_PATH/train --output_dir $OUT_PATH --batch_size_per_gpu 64 --epochs 100 \
--warmup_epochs 10  --norm_last_layer True \
--use_dense_prediction True --cfg experiments/imagenet/swin/swin_tiny_patch4_window7_224.yaml



 source deactivate
